dist: bionic
language: python
branches:
  only:
  - master
install:
- pip3 install -r requirements.txt
script:
- python3 bugs.py check
- python3 bugs.py export_database
- flake8 bugs.py
- pylint bugs.py
